//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("CustomerMessages")]
    public partial class Message
    {
        public int ClientID { get; set; }
        public int SubjectID { get; set; }
        public string Text { get; set; }
        [Key]
        public int ID { get; set; }
        
        [ForeignKey("ClientID")]
        public virtual Customer Customer { get; set; }
        [ForeignKey("SubjectID")]
        public virtual Subject Subject { get; set; }
    }
}
